accounts:
  - token: "YOUR_BOT_TOKEN"
    channels:
      - source_guild_id:
        source_channel_id:
        target_guild_id:
        target_channel_id:
      - source_guild_id:
        source_channel_id:
        target_guild_id:
        target_channel_id:
